app/models.py
from . import db, login_manager
from werkzeug.security import generate_password_hash, check_password_hash
from flask_login import UserMixin

class Post(db.Model):
	__tablename__ = 'posts'
	
	id = db.Column(db.Integer, primary_key=True)
	title = db.Column(db.String(64), nullable=False)
	body = db.Column(db.String(1028), nullable=False)
	user_id = db.Column(db.Integer, db.ForeignKey('users.id'))

	def serialize(self):
		return {
			'id': self.id,
			'title': self.title,
			'body': self.body,
			'user_id': self.user_id
		}

	def __repr__(self):
		return '<Post %r>' % self.id

class User(UserMixin, db.Model):
	__tablename__ = 'users'

	id = db.Column(db.Integer, primary_key=True)
	username = db.Column(db.String(64), unique=True)
	password_hash = db.Column(db.String(128))
	role_id = db.Column(db.Integer, db.ForeignKey('roles.id'))
	posts = db.relationship('Post', backref = 'post')

	@property
	def password(self):
		raise AttributeError('password is not a readable attribute')

	@password.setter
	def password(self, password):
		self.password_hash = generate_password_hash(password)

	def verify_password(self, password):
		return check_password_hash(self.password_hash, password)

	def serialize(self):
		return {
			'id': self.id,
			'username': self.username,
			'role_id': self.role_id
		}

	def __repr__(self):
		return '<User %r>' % self.username

class Role(db.Model):
	__tablename__ = 'roles'

	id = db.Column(db.Integer, primary_key=True)
	name = db.Column(db.String(64), unique=True)
	description = db.Column(db.String(128))
	users = db.relationship('User', backref = 'role')

	def __repr__(self):
		return '<Role %r>' % self.name

@login_manager.user_loader
def load_user(user_id):
    return User.query.get(int(user_id))

app/__init__.py
from flask import Flask
from flask_bootstrap import Bootstrap
from flask_sqlalchemy import SQLAlchemy
from flask_login import LoginManager
from config import config

bootstrap = Bootstrap()
db = SQLAlchemy()

login_manager = LoginManager()
login_manager.session_protection = 'strong'
login_manager.login_view = 'auth.login'

def create_app(config_name):
	app = Flask(__name__)
	app.config.from_object(config[config_name])
	config[config_name].init_app(app)

	bootstrap.init_app(app)
	db.init_app(app)
	login_manager.init_app(app)

	from .main import main as main_blueprint
	from .auth import auth as auth_blueprint

	app.register_blueprint(main_blueprint)
	app.register_blueprint(auth_blueprint, url_prefix='/auth')

	return app

app/main/__init__.py
from flask import Blueprint

main = Blueprint('main', __name__)

from . import views

app/main/views.py
from flask import render_template, session, redirect, url_for, jsonify
from flask_wtf import Form
from flask_login import login_required, current_user
from wtforms import StringField, PasswordField, SubmitField, BooleanField
from wtforms.validators import Required
from . import main
from .. import db
from ..models import User, Role, Post

class UserForm(Form):
	username = StringField('Username:', validators=[Required()])
	password = PasswordField('Password:', validators=[Required()])
	remember_me = BooleanField('Keep me logged in')
	submit = SubmitField('Submit')

class NewPostForm(Form):
	title = StringField('Post title:', validators=[Required()])
	body = StringField('Post body:', validators=[Required()])
	submit = SubmitField('Submit post')

@main.route('/', methods=['GET', 'POST'])
def index():
	posts = Post.query.order_by(Post.id.desc()).all()
	posts_obj = []

	for post in posts:
		user = User.query.filter_by(id=post.user_id).first()
		posts_obj.append({'post': post, 'user': user})

	return render_template("index.html", posts=posts_obj)

@main.route('/new_post', methods=['GET', 'POST'])
@login_required
def new_post():
	form = NewPostForm()

	if form.validate_on_submit():
		new_post = Post(title=form.title.data, body=form.body.data, user_id=current_user.id)
		db.session.add(new_post)
		db.session.commit()

		return redirect(url_for('main.index'))

	return render_template("new_post.html", form=form)

@main.route('/user/<username>')
def user(username):
	user = User.query.filter_by(username=username).first()

	if user is None:
		response = {
			'error': 'User not found'
		}
		return jsonify(response)

	posts = user.posts

	return render_template("profile.html", user=user, posts=posts)

app/templates/base.html
{% extends "bootstrap/base.html" %}

{% block title %}Flasky{% endblock %}

{% block head %}
{{ super() }}
<link rel="shortcut icon" href="{{ url_for('static', filename='favicon.ico') }}" type="image/x-icon">
<link rel="icon" href="{{ url_for('static', filename='favicon.ico') }}" type="image/x-icon">
{% endblock %}

{% block navbar %}
<div class="navbar navbar-inverse" role="navigation">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{{ url_for('main.index') }}">Flasky</a>
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li><a href="{{ url_for('main.index') }}">Home</a></li>
                {% if current_user.is_authenticated %}
                <li><a href="{{ url_for('main.user', username=current_user.username) }}">My Profile</a></li>
                {% endif %}
            </ul>
            <ul class="nav navbar-nav navbar-right">
                {% if current_user.is_authenticated %}
                <li><a href="{{ url_for('auth.logout') }}">Log Out</a></li>
                {% else %}
                <li><a href="{{ url_for('auth.login') }}">Log In</a></li>
                <li><a href="{{ url_for('auth.register') }}">Register</a></li>
                {% endif %}
            </ul>
        </div>
    </div>
</div>
{% endblock %}

{% block content %}
<div class="container">
    {% for message in get_flashed_messages() %}
    <div class="alert alert-warning">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        {{ message }}
    </div>
    {% endfor %}

    {% block page_content %}{% endblock %}
</div>
{% endblock %}

{% block scripts %}
{{ super() }}
{% endblock %}

app/templates/index.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %}Flasky{% endblock %}

{% block page_content %}
<div class="container">
	<div class = "page-header" style="text-align: center;">
		<h1>
		{% if current_user.is_authenticated %}
		Hello, {{ current_user.username }}!
		{% else %}
		Welcome to Flasky
		{% endif %}
		</h1>
	</div>
	<h4 style = "text-align: center;"><a href="{{ url_for('main.new_post') }}">New post</a></h4>
	{% for post in posts %}
	<div style="border: solid 1px #EEEEEE; border-radius: 5px; padding-left: 15px; margin-bottom: 20px;">
		<h3>{{post.post.title}}</h3>
		<p>{{post.post.body}}</p>
		<p>Posted by <a href="{{ url_for('main.user', username=post.user.username) }}">{{post.user.username}}</a></p>
	</div>
	{% endfor %}
</div>
{% endblock %}

app/templates/new_post.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %}Flasky{% endblock %}

{% block page_content %}
<div class="container">
	<div class = "page-header" style="text-align: center;">
		<h1>New post</h1>
	</div>
	{{ wtf.quick_form(form) }}
</div>
{% endblock %}

app/templates/profile.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %}Flasky{% endblock %}

{% block page_content %}
<div class="container">
	<div class = "page-header"">
		<h1>{{user.username}}'s profile</h1>
	</div>
	<div>
		{% if posts %}
		<h3>Posts by {{user.username}}</h3>
		{% for post in posts %}
		<h3>{{post.title}}</h3>
		<p>{{post.body}}</p>
		{% endfor %}
		{% else %}
		<h3>{{user.username}} has no posts yet</h3>
		{% endif %}
	</div>
</div>
{% endblock %}